baseURL: "https://www.niuwx.cn/"
title: "Ther's Blog"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Ther's Blog
  description: "分享技术，分享生活... "
  keywords: [Blog, C, C++, GO, Golang, 算法, 数据结构]
  author: Ther
  # images: "myimage.png"
  keywords: [c,cpp,golang,go,algorithm] 
  DateFormat: "January 2, 2006"     
  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  defaultTheme: "auto"

  disableThemeToggle: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  disableAnchoredHeadings: false
  hideMeta: false
  hideSummary: false

  showtoc: true
  tocopen: true

  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  comments: true

  analytics:
    google:
      SiteVerificationTag:	"XYZabc"

  homeInfoParams:
    Title: Welcome to my blog
    Content: |
        # Hi 👋, I'm Ther

        #### A gopher from China.

        🌱 I’m currently learning **Golang、Docker**

        👨‍💻 All of my projects are available at [https://github.com/28251536](https://github.com/28251536)

        📝 I regularly write articles on [https://www.niuwx.cn](https://www.niuwx.cn)

        💬 Ask me about **nothing, because i am rookie.**

        📫 How to reach me **28251536@qq.com**
    
  
  assets:
        favicon: "favicon.ico"
        favicon16x16: "favicon.ico"
        favicon32x32: "favicon.ico"
        apple_touch_icon: "favicon.ico"
        safari_pinned_tab: "favicon.ico"
  
  profileMode:
    enabled: false
    title: "Ther's Blog" # optional default will be site title
    subtitle: "Welcome to my blog"
    imageUrl: "touxiang.png" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Archive
        url: "/archive"
      - name: Categories
        url: "/categories"
      - name: tags
        url: /tags/
      - name: Search
        url: "/search"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/28251536"
    - name: "qq"
      url: "https://wpa.qq.com/msgrd?v=3&uin=28251536&site=qqq&menu=yes"

outputs:
    home:
        - HTML
        - RSS
        - JSON

menu:
    main:
      - identifier: Home
        name: Home
        url: "/"
        weight: 10
      - identifier: Archive
        name: Archive
        url: "/archive"
        weight: 20
      - identifier: Categories
        name: Categories
        url: "/categories"
        weight: 30
      - identifier: Tags
        name: Tags
        url: "/tags"
        weight: 40
      - identifier: Search
        name: Search
        url: "/search"
        weight: 50